import PDFDocument from "pdfkit";

export interface PayslipData {
  businessName: string;
  period: string;
  employeeName: string;
  kraPin: string | null;
  grossCents: number;
  taxableCents: number;
  payeCents: number;
  nssfEmpCents: number;
  shifCents: number;
  ahlEmpCents: number;
  netCents: number;
}

const kes = (c: number): string =>
  (c / 100).toLocaleString("en-KE", { minimumFractionDigits: 2 });

export function renderPayslipPdf(data: PayslipData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A5", margin: 36 });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(14).text(data.businessName);
    doc.fontSize(10).fillColor("#555").text(`PAYSLIP — ${data.period}`);
    doc.moveDown();
    doc.fillColor("#000").fontSize(11).text(data.employeeName);
    if (data.kraPin) doc.fontSize(9).fillColor("#555").text(`KRA PIN: ${data.kraPin}`);
    doc.moveDown();

    const row = (label: string, cents: number, bold = false): void => {
      doc
        .fontSize(bold ? 11 : 10)
        .fillColor("#000")
        .text(label, 36, doc.y, { continued: true })
        .text(`KES ${kes(cents)}`, { align: "right" });
      doc.moveDown(0.2);
    };
    row("Gross pay", data.grossCents, true);
    doc.moveDown(0.3);
    doc.fontSize(9).fillColor("#555").text("Deductions");
    row("NSSF (pension)", -data.nssfEmpCents);
    row("SHIF (health)", -data.shifCents);
    row("Affordable Housing Levy", -data.ahlEmpCents);
    row("PAYE (income tax)", -data.payeCents);
    doc.moveDown(0.3);
    doc
      .moveTo(36, doc.y)
      .lineTo(doc.page.width - 36, doc.y)
      .strokeColor("#999")
      .stroke();
    doc.moveDown(0.3);
    row("NET PAY", data.netCents, true);

    doc.moveDown();
    doc
      .fontSize(8)
      .fillColor("#777")
      .text(
        `Taxable income: KES ${kes(data.taxableCents)} (NSSF, SHIF and AHL deducted per TLAA 2024). Generated by Jenga ERP.`,
      );
    doc.end();
  });
}

export interface P10Row {
  kraPin: string | null;
  employeeName: string;
  grossCents: number;
  taxableCents: number;
  payeCents: number;
  ahlEmpCents: number;
  shifCents: number;
  nssfEmpCents: number;
}

/**
 * iTax-shaped P10/unified payroll return CSV. Column names mirror the
 * iTax bulk template semantics; exact template headers are re-verified
 * against the current iTax download at filing-feature GA.
 */
export function renderP10Csv(period: string, rows: P10Row[]): string {
  const header = [
    "PIN of Employee",
    "Name of Employee",
    "Gross Pay",
    "NSSF Contribution",
    "SHIF Contribution",
    "Affordable Housing Levy",
    "Taxable Pay",
    "PAYE Deducted",
    "Period",
  ].join(",");
  const esc = (s: string): string =>
    /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  const lines = rows.map((r) =>
    [
      r.kraPin ?? "",
      esc(r.employeeName),
      (r.grossCents / 100).toFixed(2),
      (r.nssfEmpCents / 100).toFixed(2),
      (r.shifCents / 100).toFixed(2),
      (r.ahlEmpCents / 100).toFixed(2),
      (r.taxableCents / 100).toFixed(2),
      (r.payeCents / 100).toFixed(2),
      period,
    ].join(","),
  );
  return [header, ...lines].join("\n") + "\n";
}
