import PDFDocument from "pdfkit";

export interface InvoicePdfData {
  businessName: string;
  invoiceNo: number | string;
  status: string;
  issueDate: string | null;
  customerName: string;
  customerPin: string | null;
  lines: {
    description: string;
    quantity: string | number;
    unit_price_cents: string | number;
    vat_rate: string;
    line_total_cents: string | number;
    vat_cents: string | number;
  }[];
  subtotalCents: number;
  vatCents: number;
  totalCents: number;
  fiscal: { controlNumber: string | null; qrPayload: string | null; status: string | null };
}

const kes = (c: number | string): string =>
  `KES ${(Number(c) / 100).toLocaleString("en-KE", { minimumFractionDigits: 2 })}`;

/** Render a tax invoice PDF and resolve with its bytes. */
export function renderInvoicePdf(data: InvoicePdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 48 });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(18).text(data.businessName, { continued: false });
    doc.moveDown(0.2);
    doc
      .fontSize(11)
      .fillColor("#555")
      .text(`TAX INVOICE ${data.invoiceNo ? `#${data.invoiceNo}` : "(draft)"}`)
      .text(`Date: ${data.issueDate ?? "—"}   Status: ${data.status}`);
    doc.moveDown();

    doc.fillColor("#000").fontSize(11).text("Bill to:", { underline: true });
    doc.text(data.customerName);
    if (data.customerPin) doc.text(`KRA PIN: ${data.customerPin}`);
    doc.moveDown();

    // Table header
    const xDesc = 48, xQty = 300, xPrice = 355, xVat = 440, xTotal = 490;
    doc.fontSize(9).fillColor("#555");
    doc.text("Description", xDesc, doc.y, { continued: false });
    const headerY = doc.y - 11;
    doc.text("Qty", xQty, headerY);
    doc.text("Unit", xPrice, headerY);
    doc.text("VAT", xVat, headerY);
    doc.text("Total", xTotal, headerY);
    doc.moveTo(48, doc.y + 2).lineTo(547, doc.y + 2).strokeColor("#999").stroke();
    doc.moveDown(0.4);

    doc.fillColor("#000").fontSize(10);
    for (const line of data.lines) {
      const y = doc.y;
      doc.text(line.description, xDesc, y, { width: 240 });
      const rowY = y;
      doc.text(String(Number(line.quantity)), xQty, rowY);
      doc.text(kes(line.unit_price_cents), xPrice, rowY);
      doc.text(
        line.vat_rate === "0.16" ? "16%" : line.vat_rate === "0" ? "0%" : "exempt",
        xVat,
        rowY,
      );
      doc.text(kes(line.line_total_cents), xTotal, rowY);
      doc.moveDown(0.3);
    }

    doc.moveDown();
    doc.fontSize(11);
    doc.text(`Subtotal: ${kes(data.subtotalCents)}`, 350, doc.y, { width: 200 });
    doc.text(`VAT: ${kes(data.vatCents)}`, 350, doc.y, { width: 200 });
    doc.fontSize(13).text(`TOTAL: ${kes(data.totalCents)}`, 350, doc.y, { width: 200 });

    doc.moveDown(2);
    doc.fontSize(9).fillColor("#555");
    if (data.fiscal.controlNumber) {
      doc.text(`KRA eTIMS Control Number: ${data.fiscal.controlNumber}`, 48);
      if (data.fiscal.qrPayload) doc.text(`Verify: ${data.fiscal.qrPayload}`, 48);
    } else {
      doc.text(
        `eTIMS fiscalization: ${data.fiscal.status ?? "not fiscalized"}`,
        48,
      );
    }
    doc.moveDown();
    doc.text("Generated by Jenga ERP", 48);

    doc.end();
  });
}
