import PDFDocument from "pdfkit";

export interface ReceiptPdfData {
  businessName: string;
  logo: string | null;
  receiptNumber: string;
  paymentDate: string | null; // YYYY-MM-DD
  rail: string; // cash | bank | mpesa | mpesa_c2b | stk
  customerName: string;
  customerPin: string | null;
  invoiceNo: number | string;
  amountReceivedCents: number;
  invoiceTotalCents: number;
  amountPaidToDateCents: number; // across all payments, as of now
}

const kes = (c: number | string): string =>
  `KES ${(Number(c) / 100).toLocaleString("en-KE", { minimumFractionDigits: 2 })}`;

const RAIL_LABELS: Record<string, string> = {
  cash: "Cash",
  bank: "Bank transfer / cheque",
  mpesa: "M-Pesa",
  mpesa_c2b: "M-Pesa (Paybill)",
  stk: "M-Pesa (STK push)",
};

/**
 * Official payment receipt — issued for EVERY payment, partial or full.
 * Shows the amount received on this payment plus the invoice's running
 * position (total, paid to date, balance due), so an instalment payer
 * always leaves with proof of payment and a clear remaining balance.
 */
export function renderReceiptPdf(data: ReceiptPdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A5", margin: 36, layout: "portrait" });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const left = 36;
    const right = 384; // A5 width 420pt - margin
    const width = right - left;

    // Header
    const headerY = doc.y;
    if (data.logo) {
      try {
        doc.image(data.logo, left, headerY, { height: 48 });
        doc.y = headerY + 56;
      } catch {
        // Logo failed to render, continue without it
      }
    }
    doc.fontSize(18).font("Helvetica-Bold").fillColor("#000")
      .text(data.businessName, left, doc.y);
    doc.fontSize(12).fillColor("#666").text("PAYMENT RECEIPT", left, doc.y);
    doc.moveTo(left, doc.y + 8).lineTo(right, doc.y + 8).strokeColor("#ddd").stroke();
    doc.moveDown(1.2);

    // Receipt facts
    const fact = (label: string, value: string): void => {
      const y = doc.y;
      doc.fontSize(9).font("Helvetica").fillColor("#666").text(label, left, y);
      doc.fontSize(9).font("Helvetica-Bold").fillColor("#000")
        .text(value, left + 130, y, { width: width - 130 });
      doc.moveDown(0.5);
    };
    fact("Receipt no.", data.receiptNumber);
    fact("Date", data.paymentDate ?? "—");
    fact("Received from", data.customerName + (data.customerPin ? `  (PIN ${data.customerPin})` : ""));
    fact("Payment method", RAIL_LABELS[data.rail] ?? data.rail);
    fact("Against invoice", `#${data.invoiceNo}`);

    // Amount received — the headline figure
    doc.moveDown(0.8);
    const boxY = doc.y;
    doc.roundedRect(left, boxY, width, 54, 6).fillAndStroke("#f2f7f4", "#cfe3d8");
    doc.fillColor("#496157").fontSize(9).font("Helvetica")
      .text("AMOUNT RECEIVED", left + 14, boxY + 10);
    doc.fillColor("#14532d").fontSize(18).font("Helvetica-Bold")
      .text(kes(data.amountReceivedCents), left + 14, boxY + 24);
    doc.y = boxY + 66;

    // Invoice position after this payment
    const balance = Math.max(
      0,
      data.invoiceTotalCents - data.amountPaidToDateCents,
    );
    const line = (label: string, value: string, bold = false): void => {
      const y = doc.y;
      doc.fontSize(9).font(bold ? "Helvetica-Bold" : "Helvetica")
        .fillColor(bold ? "#000" : "#666").text(label, left, y);
      doc.font(bold ? "Helvetica-Bold" : "Helvetica")
        .fillColor(bold ? "#000" : "#333")
        .text(value, left, y, { width, align: "right" });
      doc.moveDown(0.45);
    };
    line("Invoice total", kes(data.invoiceTotalCents));
    line("Paid to date (incl. this payment)", kes(data.amountPaidToDateCents));
    line("Balance due", kes(balance), true);

    doc.moveDown(0.8);
    if (balance <= 0) {
      doc.fontSize(11).font("Helvetica-Bold").fillColor("#14532d")
        .text("PAID IN FULL — thank you.", left, doc.y);
    } else {
      doc.fontSize(9).font("Helvetica").fillColor("#666")
        .text(
          `Part payment received — ${kes(balance)} remains outstanding on invoice #${data.invoiceNo}.`,
          left,
          doc.y,
          { width },
        );
    }

    doc.moveDown(1.4);
    doc.fontSize(7.5).fillColor("#999")
      .text(
        "Generated by Jenga ERP. This receipt acknowledges money received and is not a tax invoice.",
        left,
        doc.y,
        { width },
      );

    doc.end();
  });
}
